AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Core resources, components, and configuration for Ready, Set, Cloud!

Parameters:
  GitHubOwner:
    Type: String
    Default: readysetcloud
  GitHubRepo:
    Type: String
    Default: ready-set-cloud
  UpdateGitHubSourceCode:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
  AdminEmail:
    Type: String
    Default: allenheltondev@gmail.com
  BucketName:
    Type: String
  AmplifyAppId:
    Type: String
  DefaultCacheName:
    Type: String
  SendgridApiKey:
    Type: String
    NoEcho: true
  GitHubPAT:
    Type: String
    NoEcho: true
  OpenAIApiKey:
    Type: String
    NoEcho: true
  MomentoApiKey:
    Type: String
    NoEcho: true

Metadata:
  esbuild-properties: &esbuild-properties
    Format: esm
    Minify: true
    OutExtension:
      - .js=.mjs
    Target: es2020
    Sourcemap: false
    EntryPoints:
      - index.mjs
    Banner:
      - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
    External:
      - '@aws-sdk/*'

Globals:
  Function:
    Runtime: nodejs20.x
    CodeUri: functions
    Architectures:
      - arm64
    Tracing: Active
    Timeout: 3
    MemorySize: 1280
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
  TriggerAmplifyBuildFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - trigger-amplify-build.mjs
    Properties:
      Handler: trigger-amplify-build.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: amplify:StartJob
              Resource: !Sub arn:${AWS::Partition}:amplify:${AWS::Region}:${AWS::AccountId}:apps/${AmplifyAppId}/branches/master/jobs/*
      Environment:
        Variables:
          APP_ID: !Ref AmplifyAppId
      Events:
        Build:
          Type: EventBridgeRule
          Properties:
            Pattern:
              detail-type:
                - Trigger Site Rebuild

  NotifyOfBuildFailureFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - notify-of-build-failure.mjs
    Properties:
      Handler: notify-of-build-failure.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: amplify:ListJobs
              Resource: !Sub arn:${AWS::Partition}:amplify:${AWS::Region}:${AWS::AccountId}:apps/${AmplifyAppId}/branches/master/jobs/*
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref Secrets
            - Effect: Allow
              Action: events:PutEvents
              Resource: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
      Environment:
        Variables:
          APP_ID: !Ref AmplifyAppId
          OWNER: !Ref GitHubOwner
          REPO: !Ref GitHubRepo
          SECRET_ID: !Ref Secrets
      Events:
        AmplifyBuildFailed:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.amplify
              detail-type:
                - Amplify Deployment Status Change
              detail:
                appId:
                  - !Ref AmplifyAppId
                jobStatus:
                  - FAILED

  AskOpenAIFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - ask-openai.mjs
    Properties:
      Handler: ask-openai.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref Secrets
      Environment:
        Variables:
          SECRET_ID: !Ref Secrets
          CACHE_NAME: !Ref DefaultCacheName
          CACHE_TTL: 3600

  AskOpenAIParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /readysetcloud/ask-openai
      Type: String
      Value: !GetAtt AskOpenAIFunction.Arn
      Description: Arn for the Ask ChatGPT Lambda function

  SendApiRequestFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - send-api-request.mjs
    Properties:
      Handler: send-api-request.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref Secrets
      Environment:
        Variables:
          SECRET_ID: !Ref Secrets

  SendApiRequestParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /readysetcloud/send-api-request
      Type: String
      Value: !GetAtt SendApiRequestFunction.Arn
      Description: Arn for the Send API Request Lambda function

  SendEmailFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild-properties
        EntryPoints:
          - send-email.mjs
    Properties:
      Handler: send-email.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref Secrets
      Environment:
        Variables:
          SECRET_ID: !Ref Secrets
          FROM_EMAIL: !Ref AdminEmail
      Events:
        SendMailEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              detail-type:
                - Send Email

  Secrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString:
        Fn::Sub:
          - |-
            {
              "momento": "${MomentoApiKey}",
              "github": "${GitHubPAT}",
              "sendgrid":"${SendgridApiKey}",
              "openai": "${OpenAIApiKey}"
            }
          - GitHubPAT: !Ref GitHubPAT
            SendgridApiKey: !Ref SendgridApiKey
            MomentoApiKey: !Ref MomentoApiKey
            OpenAIApiKey: !Ref OpenAIApiKey

  SecretsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /readysetcloud/secrets
      Type: String
      Value: !Ref Secrets
      Description: Arn for the Secrets Manager Secret for API Keys

  GitHubOwnerParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /readysetcloud/github-owner
      Type: String
      Value: !Ref GitHubOwner
      Description: Owner of the Ready, Set, Cloud GitHub repository

  GitHubRepoParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /readysetcloud/github-repo
      Type: String
      Value: !Ref GitHubRepo
      Description: Repository name of the Ready, Set, Cloud GitHub repository

  UpdateGitHubSourceCodeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /readysetcloud/update-github-source-code
      Type: String
      Value: !Ref UpdateGitHubSourceCode
      Description: Whether to update the GitHub source code automatically

  AdminEmailParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /readysetcloud/admin-email
      Type: String
      Value: !Ref AdminEmail
      Description: Email address of the Ready, Set, Cloud administrator

  AssetsBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /readysetcloud/assets-bucket
      Type: String
      Value: !Ref BucketName
      Description: Name of the S3 bucket where static assets are stored

  AmplifyAppIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /readysetcloud/amplify-app-id
      Type: String
      Value: !Ref AmplifyAppId
      Description: App identifier for the Ready, Set, Cloud Amplify app

  CacheNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /readysetcloud/cache-name
      Type: String
      Value: !Ref DefaultCacheName
      Description: Name of the Momento cache to use by default
