name: Deploy to Production

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}

permissions:
  contents: read

env:
  BRANCH_NAME: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'push' && github.ref }}

jobs:
  predeploy-validations:
    name: Pre-deploy validations
    uses: ./.github/workflows/pre-deploy-validation.yaml

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/sam.yaml
    with:
      aws-access-key-id: ${{ secrets.PROD_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.PROD_SECRET_KEY }}
      update-github-source-code: true
      cache-name: readysetcloud
      bucket-name: readysetcloud
      amplify-app-id: ${{ secrets.PROD_AMPLIFY_APP_ID }}
      sendgrid-api-key: ${{ secrets.SENDGRID }}
      openai-api-key: ${{ secrets.OPENAI }}
      momento-api-key: ${{ secrets.MOMENTO }}
      github-pat: ${{ secrets.GITHUB }}
