name: Deploy to Stage via Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      main

concurrency:
  group: ${{ github.ref_name }}

permissions:
  contents: read

env:
  BRANCH_NAME: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref }}

jobs:
  predeploy-validations:
    name: Pre-deploy validations
    uses: ./.github/workflows/pre-deploy-validation.yaml

  deploy:
    name: Deploy
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/sam.yaml
    with:
      aws-access-key-id: ${{ secrets.STAGE_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.STAGE_SECRET_KEY }}
      update-github-source-code: false
      cache-name: readysetcloud-stage
      bucket-name: readysetcloud-stage
      amplify-app-id: ${{ secrets.STAGE_AMPLIFY_APP_ID }}
      sendgrid-api-key: ${{ secrets.SENDGRID }}
      openai-api-key: ${{ secrets.OPENAI }}
      momento-api-key: ${{ secrets.MOMENTO }}
      github-pat: ${{ secrets.GITHUB }}
    secrets: inherit

  deploy-dependabot:
    name: Deploy Dependabot Updates
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    permissions:
      pull-requests: write
      contents: write
    uses: ./.github/workflows/sam.yaml
    with:
      aws-access-key-id: ${{ secrets.DEPENDABOT_STAGE_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.DEPENDABOT_STAGE_SECRET_KEY }}
      update-github-source-code: false
      cache-name: readysetcloud-stage
      bucket-name: readysetcloud-stage
      amplify-app-id: ${{ secrets.STAGE_AMPLIFY_APP_ID }}
      sendgrid-api-key: ${{ secrets.SENDGRID }}
      openai-api-key: ${{ secrets.OPENAI }}
      momento-api-key: ${{ secrets.MOMENTO }}
      github-pat: ${{ secrets.GITHUB
    secrets: inherit

  auto-merge-dependabot-update:
    name: Auto Merge Dependabot Update
    needs: [deploy-dependabot]
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
      - uses: actions/checkout@v4
      - name: Approve a PR if not already approved
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' || steps.dependabot-metadata.outputs.package-ecosystem == 'github_actions' }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout "$PR_URL" # sets the upstream metadata for `gh pr status`

          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ]; then
            gh pr review --approve "$PR_URL"
          fi

          gh pr merge --auto --merge "$PR_URL"
