name: Deploy

on:
  workflow_call:
    inputs:
      aws-access-key-id:
        required: true
        type: string
      aws-secret-access-key:
        required: true
        type: string
      update-github-source-code:
        required: true
        type: boolean
      cache-name:
        required: true
        type: string
      bucket-name:
        required: true
        type: string
      amplify-app-id:
        required: true
        type: string
      sendgrid-api-key:
        required: true
        type: string
      github-pat:
        required: true
        type: string
      openai-api-key:
        required: true
        type: string
      momento-api-key:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}

      - name: SAM Build and Deploy
        run: |
          npm install -g esbuild
          npm ci

          sam --info
          sam build --parallel

          sam deploy \
          --stack-name rsc-core \
          --resolve-s3 \
          --no-fail-on-empty-changeset \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides UpdateGitHubSourceCode=${{ inputs.update-github-source-code }} CacheName=${{ inputs.cache-name }} BucketName=${{ inputs.bucket-name }} AmplifyAppId=${{ inputs.amplify-app-id }} SendgridApiKey=${{ inputs.sendgrid-api-key }} GitHubPAT=${{ inputs.github-pat }} MomentoApiKey=${{ inputs.momento-api-key }} OpenAIApiKey=${{ inputs.openai-api-key }}
